### ISSUE TITLE
Issue with ImageDataGeneratorCustom.py

### ISSUE THREAD

**Issue by panchinabil** [akarshzingade/image-similarity-deep-ranking#11]
Hi, 

I have been trying to get this data generator to work with my dataset and it is giving me an error, Please look into this.

Thanks
<img width="894" alt="screen shot 2018-06-13 at 10 15 14 am" src="https://user-images.githubusercontent.com/24373681/41330711-c3d14d18-6ef2-11e8-98c9-7888ebcacc77.png">

**Comment by cxfire16** [comment]
We are on the same page! 👍 
![image](https://user-images.githubusercontent.com/13092237/41333079-04f480f6-6f13-11e8-8237-98e35f7daf7d.png)

**Comment by cxfire16** [comment]
Just tested the solution in #5, it works! 👍 @akarshzingade please merge the fix to master branch to fully implement the fix. Thank you! You're awesome!

**Comment by akarshzingade** [comment]
Hey! Thank you for pointing this out. I have merged the fix into the master branch. :)
