### ISSUE TITLE
Use of batch_y in the data generator

### ISSUE THREAD

**Issue by IAmAbdusKhan** [akarshzingade/image-similarity-deep-ranking#2]
Hey Akarsh . Can you please tell me why have we put class_mode = 'categorical' . What is the use of batch_y ?

**Comment by akarshzingade** [comment]
Hey Abdus. You should neglect batch_y as it has no meaning for this particular implementation. batch_y generally contains the ground truth labels. In the case of Image Similarity, there is no such (explicit) label for a given triplet.

**Comment by IAmAbdusKhan** [comment]
Thanks mate .
