### ISSUE TITLE
Evaluation metric

### ISSUE THREAD

**Issue by IAmAbdusKhan** [akarshzingade/image-similarity-deep-ranking#3]
Hey Akarsh . Did you implement some evaluation metric also so as to quantify the results ?

**Comment by akarshzingade** [comment]
Notation: 
1) Dqp - Distance between query image and positive image.
2) Dqn - Distance between query image and negative image.
3) g - Gap parameter.

The evaluation metric would be the hinge loss. The loss should ideally be zero, which would mean that Dqp is lesser than (Dqn - 'g'). In other words, the difference between Dqp and Dqn should be less than -g. Also, if the difference between Dqp and Dqn is less than 0 (this would mean the loss is less than 'g'), the model is doing good. So, the overall hinge loss is a good evaluation metric.
