### ISSUE TITLE
ValueError: Error when checking target: expected lambda_4 to have shape (None, 4096) but got array with shape (24, 4)

### ISSUE THREAD

**Issue by vishesh9494** [akarshzingade/image-similarity-deep-ranking#7]
I have a dataset with 4 classes. I have generated the triplets.txt file with these 4 classes. 

However, when I run the deepRanking.py file, I get the following error:

`Traceback (most recent call last):
  File "deepRanking.py", line 152, in <module>
    epochs=train_epocs
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/training.py", line 2114, in fit_generator
    class_weight=class_weight)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/training.py", line 1826, in train_on_batch
    check_batch_axis=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/training.py", line 1411, in _standardize_user_data
    exception_prefix='target')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/training.py", line 153, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking target: expected lambda_4 to have shape (None, 4096) but got array with shape (24, 4)`

Need help please!

**Comment by vishesh9494** [comment]
I know the (24,4) is because I have 24 as the batch size and 4 as the number of classes. But then the last dense layer has 4096 neutrons. So why does this error occur?

**Comment by akarshzingade** [comment]
This is weird. Not sure why it would output 24x2 array. Would it be possible for you to share your dataset? I would like to locally replicate the issue.

**Comment by vishesh9494** [comment]
Hi Akarsh!

I have a dataset of 4 classes: a (576 images), b (576 images), c (320 images), d (400 images).

You can find it here - https://drive.google.com/drive/folders/1WbwXicmqDlRsp71sHGZbGKTv1bMB5MU_?usp=sharing

**Comment by akarshzingade** [comment]
Hey, Vishesh. It seems to be working fine for me. The folder structure looks like this: 

![image](https://user-images.githubusercontent.com/7059013/40572635-a3bbd764-60ce-11e8-8c91-c76a6d18e65d.png)

and the triplets file look like this:

![image](https://user-images.githubusercontent.com/7059013/40572645-cdaec81a-60ce-11e8-81c1-4ad39170d468.png)

Did you change something in the deepranking.py?

**Comment by vishesh9494** [comment]
I just edited the following lines in deepRanking.py:

![screen shot 2018-05-26 at 10 59 25 am](https://user-images.githubusercontent.com/16842897/40574517-fa32a3b6-60d3-11e8-8c25-c0900f2a966d.JPG)

![screen shot 2018-05-26 at 10 59 35 am](https://user-images.githubusercontent.com/16842897/40574518-fa659618-60d3-11e8-869b-08676ee9cbb6.JPG)

**Comment by vishesh9494** [comment]
If you have reproduced the code and its working fine, then can you upload the files (except the data) and then share the link?

**Comment by akarshzingade** [comment]
It's the same files in this repository. No change in the code.

**Comment by vishesh9494** [comment]
I cloned the repository again, added training-data and triplets.txt, and made the 2 changes shown above. But I am still getting the same error.

I have uploaded all the files in my folder - https://drive.google.com/drive/folders/1p5CgyyR6r0KNXXUecXRF4cA97nUHXut1?usp=sharing

Please see if this works for you (that is the training starts).

Thanks!

**Comment by Sanketyeru** [comment]
Where did you get ## "deepranking.h5" file from ?

**Comment by akarshinfrrd** [comment]
I just downloaded the contents of the drive link and ran the deepRanking.py. It works.
```
dense_3 (None, 4096)
lambda_4 (None, 4096)
Found 1872 images belonging to 4 classes.
Epoch 1/25

  1/629 [..............................] - ETA: 12:42:35 - loss: 1.0080

```
 This is weird. Could it be TF/Keras version mismatch? But, I doubt if it would be. I tried it on TF 1.5.0 and Keras 2.1.3 version.

**Comment by akarshzingade** [comment]
I just downloaded the contents of the drive link and ran the deepRanking.py. It works.

```
dense_3 (None, 4096)
lambda_4 (None, 4096)
Found 1872 images belonging to 4 classes.
Epoch 1/25

  1/629 [..............................] - ETA: 12:42:35 - loss: 1.0080
```

This is weird. Could it be TF/Keras version mismatch? But, I doubt if it would be. I tried it on TF 1.5.0 and Keras 2.1.3 version.

**Comment by Sanketyeru** [comment]
I have also tried same thing.
Training process starts fine but after few iterations around the first epoch 23/629 it throws error saying class array index out of bound

**Comment by cesarandreslopez** [comment]
Downloading now to test on my computer. Will report back on my results with @vishesh9494 data.

**Comment by cesarandreslopez** [comment]
Tried to run it but on that data set, it will crash after step 23 (same thing that @Sanketyeru saw). In my computer, I had to decrement the batch size due to GPU limitation and needed to run the process one epoch at a time (terminating the program after one epoch) another wise I would see a "class array index out of bound"

The model did train and is performing well after 30 epochs or so, but these epochs in my case had to be run once per script start.

**Comment by akarshzingade** [comment]
Hey, guys. For the "Array index out of bound" error, as a hacky solution for now, can you make sure that the number of triplets are a multiple of (batch_size*3)? This should work, if it doesn't, let me know.

**Comment by cesarandreslopez** [comment]
That worked. Thank you! @akarshzingade

**Comment by vishesh9494** [comment]
Hi!

I tried the code on another PC and it worked. I guess my previous machine had some issue. Well, its working fine now!

Thank you @akarshzingade @Sanketyeru @cesarandreslopez

**Comment by akarshzingade** [comment]
Awesome! Let me know if you have any other questions :)
